sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  redis:
    # host: localhost
    host: 127.0.0.1
    port: 6379
    password: 1234
    database: 0
  wechat:
    appid: wx93b33210d6b54317
    secret: 36ea71b1a2a777a8a09e754e2a74c752